import { CryptoData } from "@/types/crypto-types";
import https from "https";
import axios from "axios";
const FINNHUB_API_KEY = process.env.NEXT_PUBLIC_FINNHUB_API_KEY;
const BASE_URL = "https://finnhub.io/api/v1";


const httpsAgent = new https.Agent({
  rejectUnauthorized: false, // Disable SSL cert validation - risky!
});
export interface CryptoQuote {
  symbol: string;
  name: string;
  price: number;
  change: number;
  changePercent: number;
  volume: number;
  marketCap?: number;
  high: number;
  low: number;
  rank?: number;
  dominance?: number;
}

class CryptoAPI {
  async getCryptoQuote(symbol: string): Promise<CryptoQuote> {
    try {
      const coinId = this.getCoinId(symbol);

      const url = `https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&ids=${coinId}&sparkline=false`;

      const response = await fetch(url);
      if (!response.ok) {
        throw new Error(`Failed to fetch crypto quote: ${response.status} ${response.statusText}`);
      }

      const data = await response.json();
      const coin = data[0];

      return {
        symbol,
        name: this.getCoinName(symbol),
        price: coin.current_price || 0,
        change: coin.price_change_24h || 0,
        changePercent: coin.price_change_percentage_24h || 0,
        volume: coin.total_volume || 0,
        marketCap: coin.market_cap,
        high: coin.high_24h || 0,
        low: coin.low_24h || 0,
      };
    } catch (error) {
      console.error("Error fetching crypto quote:", error);
      throw error;
    }
  }


  async getMultipleCryptoQuotes(): Promise<CryptoData[]> {
    try {
      const response = await fetch(
        `https://api.coingecko.com/api/v3/coins/markets?vs_currency=usd&order=market_cap_desc&per_page=250&page=1&sparkline=false&price_change_percentage=24h`
      );

      if (!response.ok) {
        throw new Error("Failed to fetch crypto data");
      }

      const data = await response.json();

      return data.map((coin: any) => ({
        symbol: `${coin.symbol.toUpperCase()}-USD`,
        name: coin.name,
        price: coin.current_price || 0,
        change: coin.price_change_24h || 0,
        changePercent: coin.price_change_percentage_24h || 0,
        change24h: coin.price_change_24h || 0,
        volume: coin.total_volume || 0,
        marketCap: coin.market_cap || 0,
        high: coin.high_24h || 0,
        low: coin.low_24h || 0,
        rank: coin.market_cap_rank,
        dominance: coin.market_cap_change_percentage_24h_in_currency, // optional, you can remove or compute another way
      }));
    } catch (error) {
      console.error("❌ Error fetching multiple crypto quotes:", error);
      throw error;
    }
  }

  private getCoinId(symbol: string): string {
    const cleanedSymbol = symbol.replace("-USD", "").toUpperCase();

    // Mapping from the trading symbol to the CoinGecko API ID
    const mapping: { [key: string]: string } = {
      "1INCH": "1inch",
      AAVE: "aave",
      ADA: "cardano",
      AERO: "aerodrome-finance",
      AGIX: "singularitynet",
      ALGO: "algorand",
      AMP: "ampleforth",
      ANKR: "ankr",
      ANT: "aragon",
      APE: "apecoin",
      API3: "api3",
      APT: "aptos",
      AR: "arweave",
      ARB: "arbitrum",
      ARPA: "arpa",
      ASTR: "astar",
      ATOM: "cosmos",
      AUDIO: "audius",
      AVAX: "avalanche",
      AXS: "axie-infinity",
      BADGER: "badger-dao",
      BAL: "balancer",
      BAND: "band-protocol",
      BAT: "basic-attention-token",
      BCH: "bitcoin-cash",
      BEAM: "beam",
      BICO: "biconomy",
      BNB: "bnb",
      BOND: "barnbridge",
      BONK: "bonk",
      BORA: "bora",
      BSV: "bitcoin-sv",
      BTC: "bitcoin",
      BTG: "bitcoin-gold",
      BTSE: "btse-token",
      CELO: "celo",
      CFX: "conflux-network",
      CHZ: "chiliz",
      CKB: "nervos-network",
      COMP: "compound-governance-token",
      COTI: "coti",
      COVAL: "circuits-of-value",
      CRO: "crypto-com-chain",
      CRV: "curve-dao-token",
      CTK: "certik",
      CTSI: "cartesi",
      CTX: "cryptex-finance",
      CVC: "civic",
      CVX: "convex-finance",
      DAG: "constellation-labs",
      DAI: "dai",
      DCR: "decred",
      DESO: "deso",
      DGB: "digibyte",
      DKA: "dkargo",
      DODO: "dodo",
      DOGE: "dogecoin",
      DOT: "polkadot",
      DYDX: "dydx",
      EGLD: "egold",
      ELF: "aelf",
      ENA: "ethena",
      ENJ: "enjincoin",
      ENS: "ethereum-name-service",
      ETC: "ethereum-classic",
      ETH: "ethereum",
      ETHD: "ethereum-diamond",
      FET: "fetch-ai",
      FIL: "filecoin",
      FIS: "stafi",
      FLOKI: "floki",
      FLR: "flare-network",
      FLOW: "flow",
      FORTH: "ampleforth-governance-token",
      FTM: "fantom",
      FTT: "ftx-token",
      FUN: "funtoken",
      FXS: "frax-share",
      GALA: "gala",
      GAL: "galxe",
      GLM: "golem",
      GLMR: "moonbeam",
      GMT: "stepn",
      GNO: "gnosis",
      GRT: "the-graph",
      GT: "gatechain-token",
      GUSD: "gemini-dollar",
      HBAR: "hedera-hashgraph",
      HFT: "hashflow",
      HIVE: "hive",
      HOPR: "hopr",
      HOT: "holotoken",
      ICP: "internet-computer",
      ICX: "icon",
      ILV: "illuvium",
      IMX: "immutable-x",
      INJ: "injective-protocol",
      IOT: "helium-iot",
      IOTX: "iotex",
      IQ: "iq-cash",
      JUP: "jupiter",
      KAS: "kaspa",
      KAVA: "kava",
      KCS: "kucoin-shares",
      KDA: "kadena",
      KLAY: "klay-token",
      KSM: "kusama",
      LDO: "lido-dao",
      LEO: "leo-token",
      LINK: "chainlink",
      LOOKS: "looksrare",
      LPT: "livepeer",
      LRC: "loopring",
      LSK: "lisk",
      LTC: "litecoin",
      LUNC: "terra-luna-classic",
      MAGIC: "magic",
      MASK: "mask-network",
      MATIC: "matic-network",
      MDT: "measurable-data-token",
      METIS: "metis-token",
      MINA: "mina-protocol",
      MKR: "maker",
      MLN: "enzyme",
      MNT: "mantle",
      MSOL: "msol",
      NAKA: "nakamoto-games",
      NEAR: "near",
      NEO: "neo",
      NEXO: "nexo",
      OCEAN: "ocean-protocol",
      OKB: "okb",
      OM: "mantra-dao",
      OMI: "ecomi",
      ONE: "harmony",
      ONT: "ontology",
      OP: "optimism",
      ORDI: "ordinals",
      ORN: "orion-protocol",
      OSMO: "osmosis",
      PAXG: "pax-gold",
      PENDLE: "pendle",
      PEPE: "pepe",
      PLA: "playdapp",
      POKT: "pocket-network",
      POLY: "polymath",
      POWR: "power-ledger",
      PUNDIX: "pundi-x-2",
      PYR: "vulcan-forged",
      PYTH: "pyth-network",
      QNT: "quant-network",
      QTUM: "qtum",
      RAD: "radicle",
      REN: "ren",
      REP: "augur",
      REQ: "request",
      RETH: "rocket-pool-eth",
      RLC: "iexec-rlc",
      RNDR: "render-token",
      RON: "ronin",
      ROSE: "oasis-network",
      RPL: "rocket-pool",
      RSS: "rss3",
      RUNE: "thorchain",
      RVN: "ravencoin",
      SAND: "the-sandbox",
      SATS: "sats",
      SAVAX: "benqi-liquid-staked-avax",
      SC: "siacoin",
      SCRT: "secret",
      SDAO: "singularitydao",
      SEI: "sei-network",
      SFP: "safepal",
      SFRXETH: "staked-frax-ether",
      SGEN: "stargaze",
      SHIB: "shiba-inu",
      SKL: "skale",
      SMDX: "smardex",
      SNT: "status",
      SNX: "havven",
      SOL: "solana",
      SPELL: "spell-token",
      SRM: "serum",
      STEEM: "steem",
      STETH: "staked-ether",
      STORJ: "storj",
      STRAX: "stratis",
      STX: "blockstack",
      SUI: "sui",
      SUSHI: "sushiswap",
      SXP: "swipe",
      T: "threshold-network-token",
      TAO: "bittensor",
      TEL: "telcoin",
      THETA: "theta-token",
      TIA: "celestia",
      TKX: "tokenize-xchange",
      TLOS: "telos",
      TRB: "tellor",
      TRIBE: "tribe-2",
      TRX: "tron",
      TWT: "trust-wallet-token",
      UMA: "uma",
      UNI: "uniswap",
      USDC: "usd-coin",
      USDD: "usdd",
      USDE: "ethena-usde",
      USDT: "tether",
      USTC: "terrausd",
      VELO: "velo",
      VET: "vechain",
      VTHO: "vechain-thor-energy",
      WAXP: "wax",
      WBTC: "wrapped-bitcoin",
      WEMIX: "wemix-token",
      WETH: "weth",
      WIF: "dogwifhat",
      WLD: "worldcoin",
      WNXM: "wrapped-nxm",
      WOO: "woo-network",
      WSTETH: "wrapped-staked-ether",
      XEC: "ecash",
      XLM: "stellar",
      XMR: "monero",
      XRD: "radix",
      XRP: "xrp",
      XTZ: "tezos",
      YFI: "yearn-finance",
      ZEC: "zcash",
      ZEN: "zencash",
      ZETA: "zetachain",
      ZIL: "zilliqa",
      ZRX: "0x",
    };

    return mapping[cleanedSymbol] || cleanedSymbol.toLowerCase();
  }

  private getCoinName(symbol: string): string {
    const cleanedSymbol = symbol.replace("-USD", "").toUpperCase();

    const names: { [key: string]: string } = {
      "1INCH": "1inch",
      AAVE: "Aave",
      ADA: "Cardano",
      AERO: "Aerodrome Finance",
      AGIX: "SingularityNET",
      ALGO: "Algorand",
      AMP: "Ampleforth",
      ANKR: "Ankr",
      ANT: "Aragon",
      APE: "ApeCoin",
      API3: "API3",
      APT: "Aptos",
      AR: "Arweave",
      ARB: "Arbitrum",
      ARPA: "ARPA",
      ASTR: "Astar",
      ATOM: "Cosmos",
      AUDIO: "Audius",
      AVAX: "Avalanche",
      AXS: "Axie Infinity",
      BADGER: "Badger DAO",
      BAL: "Balancer",
      BAND: "Band Protocol",
      BAT: "Basic Attention Token",
      BCH: "Bitcoin Cash",
      BEAM: "Beam",
      BICO: "Biconomy",
      BNB: "BNB",
      BOND: "BarnBridge",
      BONK: "Bonk",
      BORA: "BORA",
      BSV: "Bitcoin SV",
      BTC: "Bitcoin",
      BTG: "Bitcoin Gold",
      BTSE: "BTSE Token",
      CELO: "Celo",
      CFX: "Conflux",
      CHZ: "Chiliz",
      CKB: "Nervos Network",
      COMP: "Compound",
      COTI: "COTI",
      COVAL: "Circuits of Value",
      CRO: "Cronos",
      CRV: "Curve DAO Token",
      CTK: "CertiK",
      CTSI: "Cartesi",
      CTX: "Cryptex Finance",
      CVC: "Civic",
      CVX: "Convex Finance",
      DAG: "Constellation",
      DAI: "Dai",
      DCR: "Decred",
      DESO: "Decentralized Social",
      DGB: "DigiByte",
      DKA: "dKargo",
      DODO: "DODO",
      DOGE: "Dogecoin",
      DOT: "Polkadot",
      DYDX: "dYdX",
      EGLD: "MultiversX",
      ELF: "aelf",
      ENA: "Ethena",
      ENJ: "Enjin Coin",
      ENS: "Ethereum Name Service",
      ETC: "Ethereum Classic",
      ETH: "Ethereum",
      ETHD: "Ethereum Diamond",
      FET: "Fetch.ai",
      FIL: "Filecoin",
      FIS: "Stafi",
      FLOKI: "FLOKI",
      FLR: "Flare",
      FLOW: "Flow",
      FORTH: "Ampleforth Governance Token",
      FTM: "Fantom",
      FTT: "FTX Token",
      FUN: "FUNToken",
      FXS: "Frax Share",
      GALA: "Gala",
      GAL: "Galxe",
      GLM: "Golem",
      GLMR: "Moonbeam",
      GMT: "GMT",
      GNO: "Gnosis",
      GRT: "The Graph",
      GT: "GateToken",
      GUSD: "Gemini Dollar",
      HBAR: "Hedera",
      HFT: "Hashflow",
      HIVE: "Hive",
      HOPR: "HOPR",
      HOT: "Holo",
      ICP: "Internet Computer",
      ICX: "ICON",
      ILV: "Illuvium",
      IMX: "Immutable",
      INJ: "Injective",
      IOT: "Helium IOT",
      IOTX: "IoTeX",
      IQ: "IQ",
      JUP: "Jupiter",
      KAS: "Kaspa",
      KAVA: "Kava",
      KCS: "KuCoin Token",
      KDA: "Kadena",
      KLAY: "Klaytn",
      KSM: "Kusama",
      LDO: "Lido DAO",
      LEO: "LEO Token",
      LINK: "Chainlink",
      LOOKS: "LooksRare",
      LPT: "Livepeer",
      LRC: "Loopring",
      LSK: "Lisk",
      LTC: "Litecoin",
      LUNC: "Terra Luna Classic",
      MAGIC: "Magic",
      MASK: "Mask Network",
      MATIC: "Polygon",
      MDT: "Measurable Data Token",
      METIS: "Metis",
      MINA: "Mina",
      MKR: "Maker",
      MLN: "Enzyme",
      MNT: "Mantle",
      MSOL: "Marinade staked SOL",
      NAKA: "Nakamoto Games",
      NEAR: "NEAR Protocol",
      NEO: "Neo",
      NEXO: "Nexo",
      OCEAN: "Ocean Protocol",
      OKB: "OKB",
      OM: "MANTRA",
      OMI: "ECOMI",
      ONE: "Harmony",
      ONT: "Ontology",
      OP: "Optimism",
      ORDI: "ORDI",
      ORN: "Orion",
      OSMO: "Osmosis",
      PAXG: "PAX Gold",
      PENDLE: "Pendle",
      PEPE: "Pepe",
      PLA: "PlayDapp",
      POKT: "Pocket Network",
      POLY: "Polymath",
      POWR: "Powerledger",
      PUNDIX: "Pundi X",
      PYR: "Vulcan Forged",
      PYTH: "Pyth Network",
      QNT: "Quant",
      QTUM: "Qtum",
      RAD: "Radicle",
      REN: "REN",
      REP: "Augur",
      REQ: "Request",
      RETH: "Rocket Pool ETH",
      RLC: "iExec RLC",
      RNDR: "Render",
      RON: "Ronin",
      ROSE: "Oasis Network",
      RPL: "Rocket Pool",
      RSS: "RSS3",
      RUNE: "THORChain",
      RVN: "Ravencoin",
      SAND: "The Sandbox",
      SATS: "Sats",
      SAVAX: "Benqi Liquid Staked AVAX",
      SC: "Siacoin",
      SCRT: "Secret",
      SDAO: "SingularityDAO",
      SEI: "Sei",
      SFP: "SafePal",
      SFRXETH: "Staked Frax Ether",
      SGEN: "Stargaze",
      SHIB: "Shiba Inu",
      SKL: "SKALE",
      SMDX: "SmarDex",
      SNT: "Status",
      SNX: "Synthetix",
      SOL: "Solana",
      SPELL: "Spell Token",
      SRM: "Serum",
      STEEM: "Steem",
      STETH: "Lido Staked Ether",
      STORJ: "Storj",
      STRAX: "Stratis",
      STX: "Stacks",
      SUI: "Sui",
      SUSHI: "SushiSwap",
      SXP: "SXP",
      T: "Threshold",
      TAO: "Bittensor",
      TEL: "Telcoin",
      THETA: "Theta Network",
      TIA: "Celestia",
      TKX: "Tokenize Xchange",
      TLOS: "Telos",
      TRB: "Tellor",
      TRIBE: "Tribe",
      TRX: "TRON",
      TWT: "Trust Wallet Token",
      UMA: "UMA",
      UNI: "Uniswap",
      USDC: "USDC",
      USDD: "USDD",
      USDE: "Ethena USDe",
      USDT: "Tether",
      USTC: "TerraClassicUSD",
      VELO: "Velo",
      VET: "VeChain",
      VTHO: "VeThor Token",
      WAXP: "WAX",
      WBTC: "Wrapped Bitcoin",
      WEMIX: "WEMIX",
      WETH: "WETH",
      WIF: "dogwifhat",
      WLD: "Worldcoin",
      WNXM: "Wrapped NXM",
      WOO: "WOO",
      WSTETH: "Wrapped liquid staked Ether 2.0",
      XEC: "eCash",
      XLM: "Stellar",
      XMR: "Monero",
      XRD: "Radix",
      XRP: "XRP",
      XTZ: "Tezos",
      YFI: "yearn.finance",
      ZEC: "Zcash",
      ZEN: "Horizen",
      ZETA: "Zetachain",
      ZIL: "Zilliqa",
      ZRX: "0x",
    };

    return names[cleanedSymbol] || cleanedSymbol;
  }

}

export const cryptoApi = new CryptoAPI();
